# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_apps.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Edit_apps(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(285, 218)
        Dialog.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Dialog.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_4.setStyleSheet("QWidget#widget_4{\n"
"    background-color:rgb(20,20,20);\n"
"    border-top-left-radius:8px;\n"
"    border-top-right-radius:8px;\n"
"    \n"
"}\n"
"QPushButton{\n"
"    background-color:rgba(0,0,0,0);\n"
"    color:rgb(144,144,144);\n"
"    font:bold;\n"
"    font-size:15px;\n"
"    font-family:entypo;\n"
"}\n"
"QPushButton:hover{\n"
"    color:rgb(142,176,27);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    pading-left:5px;\n"
"    color:rgb(91,88,53);\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.__label_3 = QtWidgets.QLabel(self.widget_4)
        self.__label_3.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.__label_3.setFont(font)
        self.__label_3.setStyleSheet("color:rgb(144,144,144);")
        self.__label_3.setObjectName("__label_3")
        self.horizontalLayout_3.addWidget(self.__label_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_5.setMinimumSize(QtCore.QSize(10, 0))
        self.pushButton_5.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_2.setStyleSheet("QWidget#widget_2{\n"
"    background-color:rgb(20,20,20);\n"
"    \n"
"}\n"
"QPushButton{\n"
"    background-color:rgba(0,0,0,0);\n"
"    color:rgb(144,144,144);\n"
"    font:bold;\n"
"    border:1px solid;\n"
"    font-size:20px;\n"
"    font-family:entypo;\n"
"}\n"
"QPushButton:hover{\n"
"    color:rgb(142,176,27);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    pading-left:5px;\n"
"    color:rgb(91,88,53);\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setObjectName("gridLayout")
        self.__label_4 = QtWidgets.QLabel(self.widget_2)
        self.__label_4.setStyleSheet("color:rgb(144,144,144);")
        self.__label_4.setObjectName("__label_4")
        self.gridLayout.addWidget(self.__label_4, 0, 0, 1, 1)
        self.__label_5 = QtWidgets.QLabel(self.widget_2)
        self.__label_5.setStyleSheet("color:rgb(144,144,144);")
        self.__label_5.setObjectName("__label_5")
        self.gridLayout.addWidget(self.__label_5, 1, 0, 1, 1)
        self.__textEdit = QtWidgets.QTextEdit(self.widget_2)
        self.__textEdit.setMaximumSize(QtCore.QSize(200, 25))
        self.__textEdit.setObjectName("__textEdit")
        self.gridLayout.addWidget(self.__textEdit, 0, 1, 1, 1)
        self.__textEdit_2 = QtWidgets.QTextEdit(self.widget_2)
        self.__textEdit_2.setMaximumSize(QtCore.QSize(200, 25))
        self.__textEdit_2.setObjectName("__textEdit_2")
        self.gridLayout.addWidget(self.__textEdit_2, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_3.setStyleSheet("QWidget#widget_3{\n"
"    background-color:rgb(20,20,20);\n"
"    border-bottom-left-radius:8px;\n"
"    border-bottom-right-radius:8px;\n"
"}\n"
"QPushButton{\n"
"    background-color:rgba(0,0,0,0);\n"
"    color:rgb(144,144,144);\n"
"    font:bold;\n"
"    font-size:20px;\n"
"    font-family:entypo;\n"
"}\n"
"QPushButton:hover{\n"
"    color:rgb(142,176,27);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    pading-left:5px;\n"
"    color:rgb(91,88,53);\n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.__label = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.__label.setFont(font)
        self.__label.setStyleSheet("color:rgb(144,144,144);\n"
"font:bold;")
        self.__label.setText("")
        self.__label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.__label.setObjectName("__label")
        self.horizontalLayout_2.addWidget(self.__label)
        self.pushButton = QtWidgets.QPushButton(self.widget_3)
        self.pushButton.setStyleSheet("border:1px;")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.__label_2 = QtWidgets.QLabel(self.widget_3)
        self.__label_2.setText("")
        self.__label_2.setObjectName("__label_2")
        self.horizontalLayout_2.addWidget(self.__label_2)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)



    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.__label_3.setText(_translate("Dialog", "EDIT APPS"))
        self.pushButton_5.setText(_translate("Dialog", "X"))
        self.__label_4.setText(_translate("Dialog", "APP NAME"))
        self.__label_5.setText(_translate("Dialog", "LINK"))
        self.__textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.__textEdit_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "Apply"))

